# Site settings
baseurl = "https://nbulischeck.io/"
themesDir = "themes"
languageCode = "en-us"
title = "Nick's Blog"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-154144453-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = ""
paginate = 20

[params]
	name = "Nick Bulischeck"
	description = "Yet Another Cybersecurity Blog"
	bio = ""
	# Enter optionally your twitter account
	twitter = "nbulischeck"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = ""
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/nbulischeck"
    github   = "https://www.github.com/nbulischeck"
